services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build: ./django-project
    container_name: hotel_search
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: ./django-project
    command: celery -A django_project worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
